package main

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

func main() {
	i := 1
	const max = 4000000
	sum := 0
	for {
		n := fib(i)
		println(n)

		if n%2 == 0 {
			sum += n
		}

		i++

		if n > max {
			break
		}
	}
	println("sum", sum)
}

// https://en.wikipedia.org/wiki/Fibonacci_number
func fib(n int) int {
	if n <= 2 {
		return 1
	}
	return fib(n-1) + fib(n-2)
}
